// ════════════════════════════════════════════════════════════════
// Forge 2.0 — AI Prompts
//
// Structured for Claude prompt caching:
//   SYSTEM_PROMPT       → cached (invariant)
//   buildCachedContext  → cached per task (architecture context)
//   buildUncachedPrompt → NOT cached (file-specific)
// ════════════════════════════════════════════════════════════════

export const SYSTEM_PROMPT = `You are Forge — an elite AI software engineer embedded inside a development team.

Your job is to write production-ready code that slots perfectly into the existing codebase.

Core principles:
- Read the provided context carefully before writing anything
- Mirror the exact coding style, naming conventions, and patterns you see
- Preserve all existing functionality when modifying files
- Add proper error handling following the codebase's patterns
- Never add unnecessary dependencies or imports
- Write self-documenting code; add brief comments only where the logic is non-obvious
- Output ONLY the requested file content — no explanations, no markdown fences`

// ── Planning prompt ───────────────────────────────────────────────

export function buildPlanPrompt(
  taskDescription: string,
  initialContext: string,
  repoFullName: string
): string {
  return `Repository: ${repoFullName}

${initialContext}

## Task
${taskDescription}

Produce a JSON implementation plan. Respond with ONLY this JSON object:

{
  "summary": "One-line summary of the change",
  "queries": ["specific search query 1", "specific search query 2"],
  "files": [
    {
      "path": "src/path/to/file.ts",
      "action": "create" | "update" | "delete",
      "reasoning": "Why this specific file needs to change"
    }
  ],
  "testCommand": "npm run test (optional)"
}

Rules:
- Use relative paths from repo root
- Be minimal — only files that genuinely need changing
- "queries" should be specific terms to find relevant code (function names, type names, patterns)`
}

// ── Cached context block (goes into the CACHED tier) ─────────────
// This is the architecture/type context, same for all files in a task.

export function buildCachedContextBlock(
  taskDescription: string,
  architectureContext: string
): string {
  return `## Task Being Implemented
${taskDescription}

${architectureContext}`
}

// ── Uncached code generation prompt (file-specific) ───────────────
// Changes per file — NOT cached.

export function buildUncachedCodePrompt(
  filePath: string,
  action: 'create' | 'update',
  fileContext: string,
  existingContent: string | null
): string {
  const parts: string[] = []

  if (fileContext.trim()) {
    parts.push(fileContext)
    parts.push('')
  }

  if (existingContent) {
    parts.push(`## Current Content of ${filePath}`)
    parts.push('```')
    parts.push(existingContent)
    parts.push('```')
    parts.push('')
  }

  parts.push(`## Your Task`)
  parts.push(
    action === 'create'
      ? `Write the complete content for the new file: ${filePath}`
      : `Update ${filePath} to implement the task described above.`
  )
  parts.push('')
  parts.push('Output ONLY the raw file content. No markdown fences. No explanation.')

  return parts.join('\n')
}

// ── Legacy single-block code gen prompt (used by Gemini) ──────────
// Gemini doesn't support prompt caching, so we send everything together.

export function buildCodeGenPrompt(
  taskDescription: string,
  codebaseContext: string,
  filePath: string,
  action: 'create' | 'update',
  existingContent: string | null
): string {
  const fileSection = existingContent
    ? `## Current Content of ${filePath}\n\`\`\`\n${existingContent}\n\`\`\``
    : `## File to Create\n${filePath} (does not exist yet)`

  return `## Task
${taskDescription}

## File: ${filePath} (action: ${action})
${fileSection}

${codebaseContext}

Write the complete, production-ready content for ${filePath}.
Output ONLY the raw file content — no markdown fences, no explanation.`
}

// ── PR description ────────────────────────────────────────────────

export function buildPRDescriptionPrompt(
  taskDescription: string,
  filesChanged: string[],
  summary: string
): string {
  return `Write a concise GitHub Pull Request description.

Task: ${taskDescription}

Files changed:
${filesChanged.map((f) => `- ${f}`).join('\n')}

Implementation summary: ${summary}

Format:
## Summary
<2-3 bullet points>

## Motivation
<1-2 sentences>

## Testing
<How to verify>

---
*Generated by Forge 2.0*`
}

// ── Commit message ────────────────────────────────────────────────

export function buildCommitMessagePrompt(
  taskDescription: string,
  filesChanged: string[]
): string {
  return `Write a git commit message.

Task: ${taskDescription}
Files: ${filesChanged.join(', ')}

Format: <type>: <description> (max 72 chars total)
Types: feat | fix | refactor | docs | style | test | chore

Output only the commit message line. No quotes. No explanation.`
}
